### ISSUE TITLE
Link Error dlsym@@GLIBC_2.17

### ISSUE THREAD

**Issue by barthm1** [Qengineering/TensorFlow_Lite_SSD_RPi_64-bits#2]
Get this error using Ubuntu 20 or RaspiOS  64

/usr/bin/ld: /root/tensorflow/tensorflow/lite/tools/make/gen/linux_aarch64/lib/libtensorflow-lite.a(interpreter_builder.o)||undefined reference to symbol 'dlsym@@GLIBC_2.17'|

**Comment by Qengineering** [comment]
As of version 2.3.0, TensorFlow uses the **d**ynamic **l**oader. 
Therefore you have to include the libdl library to your build.
On a Raspberry Pi 64-OS the symlink is `/lib/aarch64-linux-gnu/libdl.so.2`. 
I will update the Code::Blocks project file asap.

**Comment by barthm1** [comment]
Works

**Comment by Qengineering** [comment]
Updated Code::Blocks project file.

**Comment by Kant01354** [comment]
Im getting this same error - undefined reference to symbol 'dlsym@@GLIBC_2.17'|
Where and what do I need to update to fix this ?

**Comment by Qengineering** [comment]
Try adding the library with its full path: `/lib/aarch64-linux-gnu/libdl.so`
