### ISSUE TITLE
Opening the full angle of camera pi v2.

### ISSUE THREAD

**Issue by oceanle-me** [Qengineering/TensorFlow_Lite_SSD_RPi_64-bits#3]
I'm running this example, but it has a problem. When capturing camera V2, the input frames are CROPPED automatically into 640x480. This is really terrible, I want the full angle of the camrera, and rescale to 300x300 before put into the SSDv1 model.
I read the videoio.hpp but had no idea.
Please, help me to figure out directions to resolve it.
Thank you so much.

**Comment by Qengineering** [comment]
@oceanle-me,
You have two options here. 
If you capture your video with `cv::VideoCapture cap(0);` you can set the required size with
```
cv::cap.set(cv::CAP_PROP_FRAME_WIDTH,  www);
cv::cap.set(cv::CAP_PROP_FRAME_HEIGHT, hhh);
```
Please select a valid resolution. Not something like 2345x456. see [OpenCV](https://docs.opencv.org/4.2.0/d4/d15/group__videoio__flags__base.html#ggaeb8dd9c89c10a5c63c139bf7c4f5704da6223452891755166a4fd5173ea257068) 

Second option is using GStreamer. It has almost no latency. For an example see the section [YoloX + GStreamer camera](https://qengineering.eu/deep-learning-examples-on-raspberry-32-64-os.html#HandsOn)

**Comment by oceanle-me** [comment]
it works for me. My previous mistake was setting a wrong value resolution. Thank you a lot.
I'm also using GStreamer, it's really smooth
